Add responsive registration/login pages and social login buttons
ttmjltd/findclinic pull request #36
Opened 2024-08-28 06:52 UTC by suatkocar

Implemented responsive design for the registration and login pages. Added functional social login buttons. Integrated [backend changes](https://github.com/ttmjltd/findclinicsbe/pull/1/commits/787d0c8c1bfea4c28cbc67efc8801259560ea601) and opened a [Pull Request](https://github.com/ttmjltd/findclinicsbe/pulls) for Google, Facebook, and X sign-in.

![register-clinic](https://github.com/user-attachments/assets/c0a4eb9c-f999-4339-a8b2-284f4c2eb283)

2024-08-29 11:18 UTC, akayami001 requested changes

2024-08-29 11:18 UTC, akayami001 commented on package.json
> +    "@mui/icons-material": "^5.16.7",
material ui library nerede kullaniliyor? icons?

2024-08-29 11:18 UTC, akayami001 commented on app/_atoms/Input.tsx
> +const Input: React.FC<{
Inputprops extraction daha iyi olur

2024-08-29 11:31 UTC, suatkocar commented on package.json
> +    "@mui/icons-material": "^5.16.7",
Email Address - Phone Number arasındaki Toggle Switch'de kullanılıyor, tasarımın biraz dışına çıkmış bulundum çok yük getirecekse değiştirebilirim

2024-08-29 20:03 UTC, suatkocar commented
@akayami001 hocam değişikleri yaptım ancak vercel'de deploy olmuyor çözemedim local çalışıyor conflict de yok

2024-09-05 03:55 UTC, suatkocar commented
@akayami001 İstenen değişiklikleri yaptım, tekrar gözden geçirebilir misiniz?  Yapmamı istediğiniz bir şey var mı?

2024-09-05 11:06 UTC, muhsinaltintop commented
Suat Hocam mobile design'da sayfanın bir bölümü görünmüyor.
![image](https://github.com/user-attachments/assets/f2bbf23c-7f01-4534-b4fd-0908819f35c6)

2024-09-06 07:55 UTC, salihaoguz11 commented on app/register-clinic/page.tsx
> +    console.log("Code verifier saved to localStorage");
Hocam burada console kalmis. Ozellikle mi biraktiniz acaba?

2024-09-06 08:01 UTC, suatkocar commented on app/register-clinic/page.tsx
> +    console.log("Code verifier saved to localStorage");
oAuth2 sürecinde test aşamasında kalmış hocam kaldırdım

2024-09-10 08:46 UTC, merged